
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dell
 */
public class MovieWindow extends javax.swing.JFrame {
    private final ArrayList<String> movieList= new ArrayList();
    /**
     * Creates new form MovieWindow
     */
    public MovieWindow() throws FileNotFoundException {
        readFile(movieList,"İnformation.txt");
        initComponents();
        
        jRadioButton1.setText(movieList.get(1));
        jRadioButton2.setText(movieList.get(11));
        jRadioButton3.setText(movieList.get(21));
        jRadioButton4.setText(movieList.get(31));
        jRadioButton5.setText(movieList.get(41));
        jRadioButton6.setText(movieList.get(51));
        jRadioButton7.setText(movieList.get(61));
        jRadioButton8.setText(movieList.get(71));
        jRadioButton9.setText(movieList.get(81));
        jRadioButton10.setText(movieList.get(91));
        
        jRadioButton1.setActionCommand("1");
        jRadioButton2.setActionCommand("2");
        jRadioButton3.setActionCommand("3");
        jRadioButton4.setActionCommand("4");
        jRadioButton5.setActionCommand("5");
        jRadioButton6.setActionCommand("6");
        jRadioButton7.setActionCommand("7");
        jRadioButton8.setActionCommand("8");
        jRadioButton9.setActionCommand("9");
        jRadioButton10.setActionCommand("10");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jButton11 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("jRadioButton1");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("jRadioButton2");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("jRadioButton3");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("jRadioButton4");

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("jRadioButton5");

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("jRadioButton6");

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setText("jRadioButton7");

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setText("jRadioButton8");

        buttonGroup1.add(jRadioButton9);
        jRadioButton9.setText("jRadioButton9");

        buttonGroup1.add(jRadioButton10);
        jRadioButton10.setText("jRadioButton10");

        jButton11.setText("Watch");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton1.setText("İnformation");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Detailİnformation");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Back");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel1.setText("Movie");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jRadioButton4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRadioButton9))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jRadioButton1)
                                    .addGap(81, 81, 81)
                                    .addComponent(jRadioButton6))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButton2)
                                        .addComponent(jRadioButton3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButton7, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jRadioButton8, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton5)
                                .addGap(81, 81, 81)
                                .addComponent(jRadioButton10))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton11)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1)))
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jButton3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        setVisible(false);
        dispose();    
        new Main().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        setVisible(false);
        dispose();
        WatchWindow wat = new WatchWindow();
        wat.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        wat.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        setVisible(false);
        dispose(); 
        if(buttonGroup1.getSelection().getActionCommand().equals("1"))
        {  
            MovieİnformationWindow movinfo = null;
            try {
                movinfo = new MovieİnformationWindow("1");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MovieWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            movinfo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            movinfo.setVisible(true);
        }
        else if(buttonGroup1.getSelection().getActionCommand().equals("2"))
        {
            MovieİnformationWindow movinfo = null;
                try {
                    movinfo = new MovieİnformationWindow("2");
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(MovieWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            movinfo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            movinfo.setVisible(true);
        }
        else if(buttonGroup1.getSelection().getActionCommand().equals("3"))
        {
            MovieİnformationWindow movinfo = null;
                try {
                    movinfo = new MovieİnformationWindow("3");
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(MovieWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            movinfo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            movinfo.setVisible(true);
        }
        else if(buttonGroup1.getSelection().getActionCommand().equals("4"))
        {
            MovieİnformationWindow movinfo = null;
                try {
                    movinfo = new MovieİnformationWindow("4");
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(MovieWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            movinfo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            movinfo.setVisible(true);
        }
        else if(buttonGroup1.getSelection().getActionCommand().equals("5"))
        {
            MovieİnformationWindow movinfo = null;
                try {
                    movinfo = new MovieİnformationWindow("5");
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(MovieWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            movinfo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            movinfo.setVisible(true);
        }
        else if(buttonGroup1.getSelection().getActionCommand().equals("6"))
        {
            MovieİnformationWindow movinfo = null;
                try {
                    movinfo = new MovieİnformationWindow("6");
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(MovieWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            movinfo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            movinfo.setVisible(true);
        }
        else if(buttonGroup1.getSelection().getActionCommand().equals("7"))
        {
            MovieİnformationWindow movinfo = null;
                try {
                    movinfo = new MovieİnformationWindow("7");
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(MovieWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            movinfo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            movinfo.setVisible(true);
        }        
        else if(buttonGroup1.getSelection().getActionCommand().equals("8"))
        {
            MovieİnformationWindow movinfo = null;
                try {
                    movinfo = new MovieİnformationWindow("8");
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(MovieWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            movinfo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            movinfo.setVisible(true);
        }
        else if(buttonGroup1.getSelection().getActionCommand().equals("9"))
        {
            MovieİnformationWindow movinfo = null;
                try {
                    movinfo = new MovieİnformationWindow("9");
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(MovieWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            movinfo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            movinfo.setVisible(true);
        }
        else if(buttonGroup1.getSelection().getActionCommand().equals("10"))
        {
            MovieİnformationWindow movinfo = null;
                try {
                    movinfo = new MovieİnformationWindow("10");
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(MovieWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            movinfo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            movinfo.setVisible(true);
        }

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        setVisible(false);
        dispose(); 
        if(buttonGroup1.getSelection().getActionCommand().equals("1"))
        {  
            DetailİnformationWindow detinfo = null;
            try {
                detinfo = new DetailİnformationWindow("1");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MovieWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            detinfo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            detinfo.setVisible(true);
        }
        else if(buttonGroup1.getSelection().getActionCommand().equals("2"))
        {
            DetailİnformationWindow detinfo = null;
            try {
                detinfo = new DetailİnformationWindow("2");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MovieWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            detinfo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            detinfo.setVisible(true);
        }
        else if(buttonGroup1.getSelection().getActionCommand().equals("3"))
        {
            DetailİnformationWindow detinfo = null;
            try {
                detinfo = new DetailİnformationWindow("3");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MovieWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            detinfo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            detinfo.setVisible(true);
        }
        else if(buttonGroup1.getSelection().getActionCommand().equals("4"))
        {
            DetailİnformationWindow detinfo = null;
            try {
                detinfo = new DetailİnformationWindow("4");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MovieWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            detinfo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            detinfo.setVisible(true);
        }
        else if(buttonGroup1.getSelection().getActionCommand().equals("5"))
        {
            DetailİnformationWindow detinfo = null;
            try {
                detinfo = new DetailİnformationWindow("5");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MovieWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            detinfo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            detinfo.setVisible(true);
        }
        else if(buttonGroup1.getSelection().getActionCommand().equals("6"))
        {
            DetailİnformationWindow detinfo = null;
            try {
                detinfo = new DetailİnformationWindow("6");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MovieWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            detinfo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            detinfo.setVisible(true);
        }
        else if(buttonGroup1.getSelection().getActionCommand().equals("7"))
        {
            DetailİnformationWindow detinfo = null;
            try {
                detinfo = new DetailİnformationWindow("7");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MovieWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            detinfo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            detinfo.setVisible(true);
        }else if(buttonGroup1.getSelection().getActionCommand().equals("8"))
        {
            DetailİnformationWindow detinfo = null;
            try {
                detinfo = new DetailİnformationWindow("8");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MovieWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            detinfo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            detinfo.setVisible(true);
        }
        else if(buttonGroup1.getSelection().getActionCommand().equals("9"))
        {
            DetailİnformationWindow detinfo = null;
            try {
                detinfo = new DetailİnformationWindow("9");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MovieWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            detinfo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            detinfo.setVisible(true);
        }
        else if(buttonGroup1.getSelection().getActionCommand().equals("10"))
        {
            DetailİnformationWindow detinfo = null;
            try {
                detinfo = new DetailİnformationWindow("10");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MovieWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            detinfo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            detinfo.setVisible(true);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
  
    private static void readFile(List<String> originalList, String fileName) throws FileNotFoundException {
        List<String> candidateList = new ArrayList<>(1000);
        Scanner fileInput = new Scanner(new File(fileName));
        while (fileInput.hasNextLine()) {
            candidateList.add(fileInput.nextLine());
        }
        originalList.addAll(candidateList);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    // End of variables declaration//GEN-END:variables
}
